// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/sentencepiece_model.proto

#ifndef PROTOBUF_src_2fsentencepiece_5fmodel_2eproto__INCLUDED
#define PROTOBUF_src_2fsentencepiece_5fmodel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace sentencepiece {
class ModelProto;
class ModelProtoDefaultTypeInternal;
extern ModelProtoDefaultTypeInternal _ModelProto_default_instance_;
class ModelProto_SentencePiece;
class ModelProto_SentencePieceDefaultTypeInternal;
extern ModelProto_SentencePieceDefaultTypeInternal _ModelProto_SentencePiece_default_instance_;
class NormalizerSpec;
class NormalizerSpecDefaultTypeInternal;
extern NormalizerSpecDefaultTypeInternal _NormalizerSpec_default_instance_;
class TrainerSpec;
class TrainerSpecDefaultTypeInternal;
extern TrainerSpecDefaultTypeInternal _TrainerSpec_default_instance_;
}  // namespace sentencepiece

namespace sentencepiece {

namespace protobuf_src_2fsentencepiece_5fmodel_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_src_2fsentencepiece_5fmodel_2eproto

enum TrainerSpec_ModelType {
  TrainerSpec_ModelType_UNIGRAM = 1,
  TrainerSpec_ModelType_BPE = 2,
  TrainerSpec_ModelType_WORD = 3,
  TrainerSpec_ModelType_CHAR = 4
};
bool TrainerSpec_ModelType_IsValid(int value);
const TrainerSpec_ModelType TrainerSpec_ModelType_ModelType_MIN = TrainerSpec_ModelType_UNIGRAM;
const TrainerSpec_ModelType TrainerSpec_ModelType_ModelType_MAX = TrainerSpec_ModelType_CHAR;
const int TrainerSpec_ModelType_ModelType_ARRAYSIZE = TrainerSpec_ModelType_ModelType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TrainerSpec_ModelType_descriptor();
inline const ::std::string& TrainerSpec_ModelType_Name(TrainerSpec_ModelType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TrainerSpec_ModelType_descriptor(), value);
}
inline bool TrainerSpec_ModelType_Parse(
    const ::std::string& name, TrainerSpec_ModelType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TrainerSpec_ModelType>(
    TrainerSpec_ModelType_descriptor(), name, value);
}
enum ModelProto_SentencePiece_Type {
  ModelProto_SentencePiece_Type_NORMAL = 1,
  ModelProto_SentencePiece_Type_UNKNOWN = 2,
  ModelProto_SentencePiece_Type_CONTROL = 3,
  ModelProto_SentencePiece_Type_USER_DEFINED = 4
};
bool ModelProto_SentencePiece_Type_IsValid(int value);
const ModelProto_SentencePiece_Type ModelProto_SentencePiece_Type_Type_MIN = ModelProto_SentencePiece_Type_NORMAL;
const ModelProto_SentencePiece_Type ModelProto_SentencePiece_Type_Type_MAX = ModelProto_SentencePiece_Type_USER_DEFINED;
const int ModelProto_SentencePiece_Type_Type_ARRAYSIZE = ModelProto_SentencePiece_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ModelProto_SentencePiece_Type_descriptor();
inline const ::std::string& ModelProto_SentencePiece_Type_Name(ModelProto_SentencePiece_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ModelProto_SentencePiece_Type_descriptor(), value);
}
inline bool ModelProto_SentencePiece_Type_Parse(
    const ::std::string& name, ModelProto_SentencePiece_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ModelProto_SentencePiece_Type>(
    ModelProto_SentencePiece_Type_descriptor(), name, value);
}
// ===================================================================

class TrainerSpec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sentencepiece.TrainerSpec) */ {
 public:
  TrainerSpec();
  virtual ~TrainerSpec();

  TrainerSpec(const TrainerSpec& from);

  inline TrainerSpec& operator=(const TrainerSpec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrainerSpec& default_instance();

  static inline const TrainerSpec* internal_default_instance() {
    return reinterpret_cast<const TrainerSpec*>(
               &_TrainerSpec_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TrainerSpec* other);

  // implements Message ----------------------------------------------

  inline TrainerSpec* New() const PROTOBUF_FINAL { return New(NULL); }

  TrainerSpec* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TrainerSpec& from);
  void MergeFrom(const TrainerSpec& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TrainerSpec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef TrainerSpec_ModelType ModelType;
  static const ModelType UNIGRAM =
    TrainerSpec_ModelType_UNIGRAM;
  static const ModelType BPE =
    TrainerSpec_ModelType_BPE;
  static const ModelType WORD =
    TrainerSpec_ModelType_WORD;
  static const ModelType CHAR =
    TrainerSpec_ModelType_CHAR;
  static inline bool ModelType_IsValid(int value) {
    return TrainerSpec_ModelType_IsValid(value);
  }
  static const ModelType ModelType_MIN =
    TrainerSpec_ModelType_ModelType_MIN;
  static const ModelType ModelType_MAX =
    TrainerSpec_ModelType_ModelType_MAX;
  static const int ModelType_ARRAYSIZE =
    TrainerSpec_ModelType_ModelType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ModelType_descriptor() {
    return TrainerSpec_ModelType_descriptor();
  }
  static inline const ::std::string& ModelType_Name(ModelType value) {
    return TrainerSpec_ModelType_Name(value);
  }
  static inline bool ModelType_Parse(const ::std::string& name,
      ModelType* value) {
    return TrainerSpec_ModelType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated string input = 1;
  int input_size() const;
  void clear_input();
  static const int kInputFieldNumber = 1;
  const ::std::string& input(int index) const;
  ::std::string* mutable_input(int index);
  void set_input(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_input(int index, ::std::string&& value);
  #endif
  void set_input(int index, const char* value);
  void set_input(int index, const char* value, size_t size);
  ::std::string* add_input();
  void add_input(const ::std::string& value);
  #if LANG_CXX11
  void add_input(::std::string&& value);
  #endif
  void add_input(const char* value);
  void add_input(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& input() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_input();

  // repeated string accept_language = 5;
  int accept_language_size() const;
  void clear_accept_language();
  static const int kAcceptLanguageFieldNumber = 5;
  const ::std::string& accept_language(int index) const;
  ::std::string* mutable_accept_language(int index);
  void set_accept_language(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_accept_language(int index, ::std::string&& value);
  #endif
  void set_accept_language(int index, const char* value);
  void set_accept_language(int index, const char* value, size_t size);
  ::std::string* add_accept_language();
  void add_accept_language(const ::std::string& value);
  #if LANG_CXX11
  void add_accept_language(::std::string&& value);
  #endif
  void add_accept_language(const char* value);
  void add_accept_language(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& accept_language() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_accept_language();

  // repeated string control_symbols = 30;
  int control_symbols_size() const;
  void clear_control_symbols();
  static const int kControlSymbolsFieldNumber = 30;
  const ::std::string& control_symbols(int index) const;
  ::std::string* mutable_control_symbols(int index);
  void set_control_symbols(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_control_symbols(int index, ::std::string&& value);
  #endif
  void set_control_symbols(int index, const char* value);
  void set_control_symbols(int index, const char* value, size_t size);
  ::std::string* add_control_symbols();
  void add_control_symbols(const ::std::string& value);
  #if LANG_CXX11
  void add_control_symbols(::std::string&& value);
  #endif
  void add_control_symbols(const char* value);
  void add_control_symbols(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& control_symbols() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_control_symbols();

  // repeated string user_defined_symbols = 31;
  int user_defined_symbols_size() const;
  void clear_user_defined_symbols();
  static const int kUserDefinedSymbolsFieldNumber = 31;
  const ::std::string& user_defined_symbols(int index) const;
  ::std::string* mutable_user_defined_symbols(int index);
  void set_user_defined_symbols(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_user_defined_symbols(int index, ::std::string&& value);
  #endif
  void set_user_defined_symbols(int index, const char* value);
  void set_user_defined_symbols(int index, const char* value, size_t size);
  ::std::string* add_user_defined_symbols();
  void add_user_defined_symbols(const ::std::string& value);
  #if LANG_CXX11
  void add_user_defined_symbols(::std::string&& value);
  #endif
  void add_user_defined_symbols(const char* value);
  void add_user_defined_symbols(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& user_defined_symbols() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_user_defined_symbols();

  // optional string model_prefix = 2;
  bool has_model_prefix() const;
  void clear_model_prefix();
  static const int kModelPrefixFieldNumber = 2;
  const ::std::string& model_prefix() const;
  void set_model_prefix(const ::std::string& value);
  #if LANG_CXX11
  void set_model_prefix(::std::string&& value);
  #endif
  void set_model_prefix(const char* value);
  void set_model_prefix(const char* value, size_t size);
  ::std::string* mutable_model_prefix();
  ::std::string* release_model_prefix();
  void set_allocated_model_prefix(::std::string* model_prefix);

  // optional .sentencepiece.TrainerSpec.ModelType model_type = 3 [default = UNIGRAM];
  bool has_model_type() const;
  void clear_model_type();
  static const int kModelTypeFieldNumber = 3;
  ::sentencepiece::TrainerSpec_ModelType model_type() const;
  void set_model_type(::sentencepiece::TrainerSpec_ModelType value);

  // optional int32 vocab_size = 4 [default = 8000];
  bool has_vocab_size() const;
  void clear_vocab_size();
  static const int kVocabSizeFieldNumber = 4;
  ::google::protobuf::int32 vocab_size() const;
  void set_vocab_size(::google::protobuf::int32 value);

  // optional float character_coverage = 10 [default = 0.9995];
  bool has_character_coverage() const;
  void clear_character_coverage();
  static const int kCharacterCoverageFieldNumber = 10;
  float character_coverage() const;
  void set_character_coverage(float value);

  // optional int32 input_sentence_size = 11 [default = 10000000];
  bool has_input_sentence_size() const;
  void clear_input_sentence_size();
  static const int kInputSentenceSizeFieldNumber = 11;
  ::google::protobuf::int32 input_sentence_size() const;
  void set_input_sentence_size(::google::protobuf::int32 value);

  // optional int32 mining_sentence_size = 12 [default = 2000000];
  bool has_mining_sentence_size() const;
  void clear_mining_sentence_size();
  static const int kMiningSentenceSizeFieldNumber = 12;
  ::google::protobuf::int32 mining_sentence_size() const;
  void set_mining_sentence_size(::google::protobuf::int32 value);

  // optional int32 training_sentence_size = 13 [default = 10000000];
  bool has_training_sentence_size() const;
  void clear_training_sentence_size();
  static const int kTrainingSentenceSizeFieldNumber = 13;
  ::google::protobuf::int32 training_sentence_size() const;
  void set_training_sentence_size(::google::protobuf::int32 value);

  // optional int32 seed_sentencepiece_size = 14 [default = 1000000];
  bool has_seed_sentencepiece_size() const;
  void clear_seed_sentencepiece_size();
  static const int kSeedSentencepieceSizeFieldNumber = 14;
  ::google::protobuf::int32 seed_sentencepiece_size() const;
  void set_seed_sentencepiece_size(::google::protobuf::int32 value);

  // optional float shrinking_factor = 15 [default = 0.75];
  bool has_shrinking_factor() const;
  void clear_shrinking_factor();
  static const int kShrinkingFactorFieldNumber = 15;
  float shrinking_factor() const;
  void set_shrinking_factor(float value);

  // optional int32 num_threads = 16 [default = 16];
  bool has_num_threads() const;
  void clear_num_threads();
  static const int kNumThreadsFieldNumber = 16;
  ::google::protobuf::int32 num_threads() const;
  void set_num_threads(::google::protobuf::int32 value);

  // optional int32 num_sub_iterations = 17 [default = 2];
  bool has_num_sub_iterations() const;
  void clear_num_sub_iterations();
  static const int kNumSubIterationsFieldNumber = 17;
  ::google::protobuf::int32 num_sub_iterations() const;
  void set_num_sub_iterations(::google::protobuf::int32 value);

  // optional int32 max_sentencepiece_length = 20 [default = 16];
  bool has_max_sentencepiece_length() const;
  void clear_max_sentencepiece_length();
  static const int kMaxSentencepieceLengthFieldNumber = 20;
  ::google::protobuf::int32 max_sentencepiece_length() const;
  void set_max_sentencepiece_length(::google::protobuf::int32 value);

  // optional bool split_by_unicode_script = 21 [default = true];
  bool has_split_by_unicode_script() const;
  void clear_split_by_unicode_script();
  static const int kSplitByUnicodeScriptFieldNumber = 21;
  bool split_by_unicode_script() const;
  void set_split_by_unicode_script(bool value);

  // optional bool split_by_whitespace = 22 [default = true];
  bool has_split_by_whitespace() const;
  void clear_split_by_whitespace();
  static const int kSplitByWhitespaceFieldNumber = 22;
  bool split_by_whitespace() const;
  void set_split_by_whitespace(bool value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(TrainerSpec)
  // @@protoc_insertion_point(class_scope:sentencepiece.TrainerSpec)
 private:
  void set_has_model_prefix();
  void clear_has_model_prefix();
  void set_has_model_type();
  void clear_has_model_type();
  void set_has_vocab_size();
  void clear_has_vocab_size();
  void set_has_character_coverage();
  void clear_has_character_coverage();
  void set_has_input_sentence_size();
  void clear_has_input_sentence_size();
  void set_has_mining_sentence_size();
  void clear_has_mining_sentence_size();
  void set_has_training_sentence_size();
  void clear_has_training_sentence_size();
  void set_has_seed_sentencepiece_size();
  void clear_has_seed_sentencepiece_size();
  void set_has_shrinking_factor();
  void clear_has_shrinking_factor();
  void set_has_num_threads();
  void clear_has_num_threads();
  void set_has_num_sub_iterations();
  void clear_has_num_sub_iterations();
  void set_has_max_sentencepiece_length();
  void clear_has_max_sentencepiece_length();
  void set_has_split_by_unicode_script();
  void clear_has_split_by_unicode_script();
  void set_has_split_by_whitespace();
  void clear_has_split_by_whitespace();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> input_;
  ::google::protobuf::RepeatedPtrField< ::std::string> accept_language_;
  ::google::protobuf::RepeatedPtrField< ::std::string> control_symbols_;
  ::google::protobuf::RepeatedPtrField< ::std::string> user_defined_symbols_;
  ::google::protobuf::internal::ArenaStringPtr model_prefix_;
  int model_type_;
  ::google::protobuf::int32 vocab_size_;
  float character_coverage_;
  ::google::protobuf::int32 input_sentence_size_;
  ::google::protobuf::int32 mining_sentence_size_;
  ::google::protobuf::int32 training_sentence_size_;
  ::google::protobuf::int32 seed_sentencepiece_size_;
  float shrinking_factor_;
  ::google::protobuf::int32 num_threads_;
  ::google::protobuf::int32 num_sub_iterations_;
  ::google::protobuf::int32 max_sentencepiece_length_;
  bool split_by_unicode_script_;
  bool split_by_whitespace_;
  friend struct protobuf_src_2fsentencepiece_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NormalizerSpec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sentencepiece.NormalizerSpec) */ {
 public:
  NormalizerSpec();
  virtual ~NormalizerSpec();

  NormalizerSpec(const NormalizerSpec& from);

  inline NormalizerSpec& operator=(const NormalizerSpec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NormalizerSpec& default_instance();

  static inline const NormalizerSpec* internal_default_instance() {
    return reinterpret_cast<const NormalizerSpec*>(
               &_NormalizerSpec_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NormalizerSpec* other);

  // implements Message ----------------------------------------------

  inline NormalizerSpec* New() const PROTOBUF_FINAL { return New(NULL); }

  NormalizerSpec* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NormalizerSpec& from);
  void MergeFrom(const NormalizerSpec& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NormalizerSpec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional bytes precompiled_charsmap = 2;
  bool has_precompiled_charsmap() const;
  void clear_precompiled_charsmap();
  static const int kPrecompiledCharsmapFieldNumber = 2;
  const ::std::string& precompiled_charsmap() const;
  void set_precompiled_charsmap(const ::std::string& value);
  #if LANG_CXX11
  void set_precompiled_charsmap(::std::string&& value);
  #endif
  void set_precompiled_charsmap(const char* value);
  void set_precompiled_charsmap(const void* value, size_t size);
  ::std::string* mutable_precompiled_charsmap();
  ::std::string* release_precompiled_charsmap();
  void set_allocated_precompiled_charsmap(::std::string* precompiled_charsmap);

  // optional bool add_dummy_prefix = 3 [default = true];
  bool has_add_dummy_prefix() const;
  void clear_add_dummy_prefix();
  static const int kAddDummyPrefixFieldNumber = 3;
  bool add_dummy_prefix() const;
  void set_add_dummy_prefix(bool value);

  // optional bool remove_extra_whitespaces = 4 [default = true];
  bool has_remove_extra_whitespaces() const;
  void clear_remove_extra_whitespaces();
  static const int kRemoveExtraWhitespacesFieldNumber = 4;
  bool remove_extra_whitespaces() const;
  void set_remove_extra_whitespaces(bool value);

  // optional bool escape_whitespaces = 5 [default = true];
  bool has_escape_whitespaces() const;
  void clear_escape_whitespaces();
  static const int kEscapeWhitespacesFieldNumber = 5;
  bool escape_whitespaces() const;
  void set_escape_whitespaces(bool value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(NormalizerSpec)
  // @@protoc_insertion_point(class_scope:sentencepiece.NormalizerSpec)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_precompiled_charsmap();
  void clear_has_precompiled_charsmap();
  void set_has_add_dummy_prefix();
  void clear_has_add_dummy_prefix();
  void set_has_remove_extra_whitespaces();
  void clear_has_remove_extra_whitespaces();
  void set_has_escape_whitespaces();
  void clear_has_escape_whitespaces();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr precompiled_charsmap_;
  bool add_dummy_prefix_;
  bool remove_extra_whitespaces_;
  bool escape_whitespaces_;
  friend struct protobuf_src_2fsentencepiece_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModelProto_SentencePiece : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sentencepiece.ModelProto.SentencePiece) */ {
 public:
  ModelProto_SentencePiece();
  virtual ~ModelProto_SentencePiece();

  ModelProto_SentencePiece(const ModelProto_SentencePiece& from);

  inline ModelProto_SentencePiece& operator=(const ModelProto_SentencePiece& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelProto_SentencePiece& default_instance();

  static inline const ModelProto_SentencePiece* internal_default_instance() {
    return reinterpret_cast<const ModelProto_SentencePiece*>(
               &_ModelProto_SentencePiece_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ModelProto_SentencePiece* other);

  // implements Message ----------------------------------------------

  inline ModelProto_SentencePiece* New() const PROTOBUF_FINAL { return New(NULL); }

  ModelProto_SentencePiece* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ModelProto_SentencePiece& from);
  void MergeFrom(const ModelProto_SentencePiece& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ModelProto_SentencePiece* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ModelProto_SentencePiece_Type Type;
  static const Type NORMAL =
    ModelProto_SentencePiece_Type_NORMAL;
  static const Type UNKNOWN =
    ModelProto_SentencePiece_Type_UNKNOWN;
  static const Type CONTROL =
    ModelProto_SentencePiece_Type_CONTROL;
  static const Type USER_DEFINED =
    ModelProto_SentencePiece_Type_USER_DEFINED;
  static inline bool Type_IsValid(int value) {
    return ModelProto_SentencePiece_Type_IsValid(value);
  }
  static const Type Type_MIN =
    ModelProto_SentencePiece_Type_Type_MIN;
  static const Type Type_MAX =
    ModelProto_SentencePiece_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    ModelProto_SentencePiece_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return ModelProto_SentencePiece_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return ModelProto_SentencePiece_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return ModelProto_SentencePiece_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string piece = 1;
  bool has_piece() const;
  void clear_piece();
  static const int kPieceFieldNumber = 1;
  const ::std::string& piece() const;
  void set_piece(const ::std::string& value);
  #if LANG_CXX11
  void set_piece(::std::string&& value);
  #endif
  void set_piece(const char* value);
  void set_piece(const char* value, size_t size);
  ::std::string* mutable_piece();
  ::std::string* release_piece();
  void set_allocated_piece(::std::string* piece);

  // optional float score = 2;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  float score() const;
  void set_score(float value);

  // optional .sentencepiece.ModelProto.SentencePiece.Type type = 3 [default = NORMAL];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::sentencepiece::ModelProto_SentencePiece_Type type() const;
  void set_type(::sentencepiece::ModelProto_SentencePiece_Type value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ModelProto_SentencePiece)
  // @@protoc_insertion_point(class_scope:sentencepiece.ModelProto.SentencePiece)
 private:
  void set_has_piece();
  void clear_has_piece();
  void set_has_score();
  void clear_has_score();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr piece_;
  float score_;
  int type_;
  friend struct protobuf_src_2fsentencepiece_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModelProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sentencepiece.ModelProto) */ {
 public:
  ModelProto();
  virtual ~ModelProto();

  ModelProto(const ModelProto& from);

  inline ModelProto& operator=(const ModelProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelProto& default_instance();

  static inline const ModelProto* internal_default_instance() {
    return reinterpret_cast<const ModelProto*>(
               &_ModelProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ModelProto* other);

  // implements Message ----------------------------------------------

  inline ModelProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ModelProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ModelProto& from);
  void MergeFrom(const ModelProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ModelProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ModelProto_SentencePiece SentencePiece;

  // accessors -------------------------------------------------------

  // repeated .sentencepiece.ModelProto.SentencePiece pieces = 1;
  int pieces_size() const;
  void clear_pieces();
  static const int kPiecesFieldNumber = 1;
  const ::sentencepiece::ModelProto_SentencePiece& pieces(int index) const;
  ::sentencepiece::ModelProto_SentencePiece* mutable_pieces(int index);
  ::sentencepiece::ModelProto_SentencePiece* add_pieces();
  ::google::protobuf::RepeatedPtrField< ::sentencepiece::ModelProto_SentencePiece >*
      mutable_pieces();
  const ::google::protobuf::RepeatedPtrField< ::sentencepiece::ModelProto_SentencePiece >&
      pieces() const;

  // optional .sentencepiece.TrainerSpec trainer_spec = 2;
  bool has_trainer_spec() const;
  void clear_trainer_spec();
  static const int kTrainerSpecFieldNumber = 2;
  const ::sentencepiece::TrainerSpec& trainer_spec() const;
  ::sentencepiece::TrainerSpec* mutable_trainer_spec();
  ::sentencepiece::TrainerSpec* release_trainer_spec();
  void set_allocated_trainer_spec(::sentencepiece::TrainerSpec* trainer_spec);

  // optional .sentencepiece.NormalizerSpec normalizer_spec = 3;
  bool has_normalizer_spec() const;
  void clear_normalizer_spec();
  static const int kNormalizerSpecFieldNumber = 3;
  const ::sentencepiece::NormalizerSpec& normalizer_spec() const;
  ::sentencepiece::NormalizerSpec* mutable_normalizer_spec();
  ::sentencepiece::NormalizerSpec* release_normalizer_spec();
  void set_allocated_normalizer_spec(::sentencepiece::NormalizerSpec* normalizer_spec);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ModelProto)
  // @@protoc_insertion_point(class_scope:sentencepiece.ModelProto)
 private:
  void set_has_trainer_spec();
  void clear_has_trainer_spec();
  void set_has_normalizer_spec();
  void clear_has_normalizer_spec();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::sentencepiece::ModelProto_SentencePiece > pieces_;
  ::sentencepiece::TrainerSpec* trainer_spec_;
  ::sentencepiece::NormalizerSpec* normalizer_spec_;
  friend struct protobuf_src_2fsentencepiece_5fmodel_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TrainerSpec

// repeated string input = 1;
inline int TrainerSpec::input_size() const {
  return input_.size();
}
inline void TrainerSpec::clear_input() {
  input_.Clear();
}
inline const ::std::string& TrainerSpec::input(int index) const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.input)
  return input_.Get(index);
}
inline ::std::string* TrainerSpec::mutable_input(int index) {
  // @@protoc_insertion_point(field_mutable:sentencepiece.TrainerSpec.input)
  return input_.Mutable(index);
}
inline void TrainerSpec::set_input(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.input)
  input_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void TrainerSpec::set_input(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.input)
  input_.Mutable(index)->assign(std::move(value));
}
#endif
inline void TrainerSpec::set_input(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  input_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sentencepiece.TrainerSpec.input)
}
inline void TrainerSpec::set_input(int index, const char* value, size_t size) {
  input_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.TrainerSpec.input)
}
inline ::std::string* TrainerSpec::add_input() {
  // @@protoc_insertion_point(field_add_mutable:sentencepiece.TrainerSpec.input)
  return input_.Add();
}
inline void TrainerSpec::add_input(const ::std::string& value) {
  input_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.input)
}
#if LANG_CXX11
inline void TrainerSpec::add_input(::std::string&& value) {
  input_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.input)
}
#endif
inline void TrainerSpec::add_input(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  input_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sentencepiece.TrainerSpec.input)
}
inline void TrainerSpec::add_input(const char* value, size_t size) {
  input_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sentencepiece.TrainerSpec.input)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TrainerSpec::input() const {
  // @@protoc_insertion_point(field_list:sentencepiece.TrainerSpec.input)
  return input_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TrainerSpec::mutable_input() {
  // @@protoc_insertion_point(field_mutable_list:sentencepiece.TrainerSpec.input)
  return &input_;
}

// optional string model_prefix = 2;
inline bool TrainerSpec::has_model_prefix() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TrainerSpec::set_has_model_prefix() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TrainerSpec::clear_has_model_prefix() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TrainerSpec::clear_model_prefix() {
  model_prefix_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_model_prefix();
}
inline const ::std::string& TrainerSpec::model_prefix() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.model_prefix)
  return model_prefix_.GetNoArena();
}
inline void TrainerSpec::set_model_prefix(const ::std::string& value) {
  set_has_model_prefix();
  model_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.model_prefix)
}
#if LANG_CXX11
inline void TrainerSpec::set_model_prefix(::std::string&& value) {
  set_has_model_prefix();
  model_prefix_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sentencepiece.TrainerSpec.model_prefix)
}
#endif
inline void TrainerSpec::set_model_prefix(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_model_prefix();
  model_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sentencepiece.TrainerSpec.model_prefix)
}
inline void TrainerSpec::set_model_prefix(const char* value, size_t size) {
  set_has_model_prefix();
  model_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.TrainerSpec.model_prefix)
}
inline ::std::string* TrainerSpec::mutable_model_prefix() {
  set_has_model_prefix();
  // @@protoc_insertion_point(field_mutable:sentencepiece.TrainerSpec.model_prefix)
  return model_prefix_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TrainerSpec::release_model_prefix() {
  // @@protoc_insertion_point(field_release:sentencepiece.TrainerSpec.model_prefix)
  clear_has_model_prefix();
  return model_prefix_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TrainerSpec::set_allocated_model_prefix(::std::string* model_prefix) {
  if (model_prefix != NULL) {
    set_has_model_prefix();
  } else {
    clear_has_model_prefix();
  }
  model_prefix_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_prefix);
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.TrainerSpec.model_prefix)
}

// optional .sentencepiece.TrainerSpec.ModelType model_type = 3 [default = UNIGRAM];
inline bool TrainerSpec::has_model_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TrainerSpec::set_has_model_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TrainerSpec::clear_has_model_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TrainerSpec::clear_model_type() {
  model_type_ = 1;
  clear_has_model_type();
}
inline ::sentencepiece::TrainerSpec_ModelType TrainerSpec::model_type() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.model_type)
  return static_cast< ::sentencepiece::TrainerSpec_ModelType >(model_type_);
}
inline void TrainerSpec::set_model_type(::sentencepiece::TrainerSpec_ModelType value) {
  assert(::sentencepiece::TrainerSpec_ModelType_IsValid(value));
  set_has_model_type();
  model_type_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.model_type)
}

// optional int32 vocab_size = 4 [default = 8000];
inline bool TrainerSpec::has_vocab_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TrainerSpec::set_has_vocab_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TrainerSpec::clear_has_vocab_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TrainerSpec::clear_vocab_size() {
  vocab_size_ = 8000;
  clear_has_vocab_size();
}
inline ::google::protobuf::int32 TrainerSpec::vocab_size() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.vocab_size)
  return vocab_size_;
}
inline void TrainerSpec::set_vocab_size(::google::protobuf::int32 value) {
  set_has_vocab_size();
  vocab_size_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.vocab_size)
}

// repeated string accept_language = 5;
inline int TrainerSpec::accept_language_size() const {
  return accept_language_.size();
}
inline void TrainerSpec::clear_accept_language() {
  accept_language_.Clear();
}
inline const ::std::string& TrainerSpec::accept_language(int index) const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.accept_language)
  return accept_language_.Get(index);
}
inline ::std::string* TrainerSpec::mutable_accept_language(int index) {
  // @@protoc_insertion_point(field_mutable:sentencepiece.TrainerSpec.accept_language)
  return accept_language_.Mutable(index);
}
inline void TrainerSpec::set_accept_language(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.accept_language)
  accept_language_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void TrainerSpec::set_accept_language(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.accept_language)
  accept_language_.Mutable(index)->assign(std::move(value));
}
#endif
inline void TrainerSpec::set_accept_language(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  accept_language_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sentencepiece.TrainerSpec.accept_language)
}
inline void TrainerSpec::set_accept_language(int index, const char* value, size_t size) {
  accept_language_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.TrainerSpec.accept_language)
}
inline ::std::string* TrainerSpec::add_accept_language() {
  // @@protoc_insertion_point(field_add_mutable:sentencepiece.TrainerSpec.accept_language)
  return accept_language_.Add();
}
inline void TrainerSpec::add_accept_language(const ::std::string& value) {
  accept_language_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.accept_language)
}
#if LANG_CXX11
inline void TrainerSpec::add_accept_language(::std::string&& value) {
  accept_language_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.accept_language)
}
#endif
inline void TrainerSpec::add_accept_language(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  accept_language_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sentencepiece.TrainerSpec.accept_language)
}
inline void TrainerSpec::add_accept_language(const char* value, size_t size) {
  accept_language_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sentencepiece.TrainerSpec.accept_language)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TrainerSpec::accept_language() const {
  // @@protoc_insertion_point(field_list:sentencepiece.TrainerSpec.accept_language)
  return accept_language_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TrainerSpec::mutable_accept_language() {
  // @@protoc_insertion_point(field_mutable_list:sentencepiece.TrainerSpec.accept_language)
  return &accept_language_;
}

// optional float character_coverage = 10 [default = 0.9995];
inline bool TrainerSpec::has_character_coverage() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TrainerSpec::set_has_character_coverage() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TrainerSpec::clear_has_character_coverage() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TrainerSpec::clear_character_coverage() {
  character_coverage_ = 0.9995f;
  clear_has_character_coverage();
}
inline float TrainerSpec::character_coverage() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.character_coverage)
  return character_coverage_;
}
inline void TrainerSpec::set_character_coverage(float value) {
  set_has_character_coverage();
  character_coverage_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.character_coverage)
}

// optional int32 input_sentence_size = 11 [default = 10000000];
inline bool TrainerSpec::has_input_sentence_size() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TrainerSpec::set_has_input_sentence_size() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TrainerSpec::clear_has_input_sentence_size() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TrainerSpec::clear_input_sentence_size() {
  input_sentence_size_ = 10000000;
  clear_has_input_sentence_size();
}
inline ::google::protobuf::int32 TrainerSpec::input_sentence_size() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.input_sentence_size)
  return input_sentence_size_;
}
inline void TrainerSpec::set_input_sentence_size(::google::protobuf::int32 value) {
  set_has_input_sentence_size();
  input_sentence_size_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.input_sentence_size)
}

// optional int32 mining_sentence_size = 12 [default = 2000000];
inline bool TrainerSpec::has_mining_sentence_size() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TrainerSpec::set_has_mining_sentence_size() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TrainerSpec::clear_has_mining_sentence_size() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TrainerSpec::clear_mining_sentence_size() {
  mining_sentence_size_ = 2000000;
  clear_has_mining_sentence_size();
}
inline ::google::protobuf::int32 TrainerSpec::mining_sentence_size() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.mining_sentence_size)
  return mining_sentence_size_;
}
inline void TrainerSpec::set_mining_sentence_size(::google::protobuf::int32 value) {
  set_has_mining_sentence_size();
  mining_sentence_size_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.mining_sentence_size)
}

// optional int32 training_sentence_size = 13 [default = 10000000];
inline bool TrainerSpec::has_training_sentence_size() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TrainerSpec::set_has_training_sentence_size() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TrainerSpec::clear_has_training_sentence_size() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TrainerSpec::clear_training_sentence_size() {
  training_sentence_size_ = 10000000;
  clear_has_training_sentence_size();
}
inline ::google::protobuf::int32 TrainerSpec::training_sentence_size() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.training_sentence_size)
  return training_sentence_size_;
}
inline void TrainerSpec::set_training_sentence_size(::google::protobuf::int32 value) {
  set_has_training_sentence_size();
  training_sentence_size_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.training_sentence_size)
}

// optional int32 seed_sentencepiece_size = 14 [default = 1000000];
inline bool TrainerSpec::has_seed_sentencepiece_size() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TrainerSpec::set_has_seed_sentencepiece_size() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TrainerSpec::clear_has_seed_sentencepiece_size() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TrainerSpec::clear_seed_sentencepiece_size() {
  seed_sentencepiece_size_ = 1000000;
  clear_has_seed_sentencepiece_size();
}
inline ::google::protobuf::int32 TrainerSpec::seed_sentencepiece_size() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.seed_sentencepiece_size)
  return seed_sentencepiece_size_;
}
inline void TrainerSpec::set_seed_sentencepiece_size(::google::protobuf::int32 value) {
  set_has_seed_sentencepiece_size();
  seed_sentencepiece_size_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.seed_sentencepiece_size)
}

// optional float shrinking_factor = 15 [default = 0.75];
inline bool TrainerSpec::has_shrinking_factor() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void TrainerSpec::set_has_shrinking_factor() {
  _has_bits_[0] |= 0x00000100u;
}
inline void TrainerSpec::clear_has_shrinking_factor() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void TrainerSpec::clear_shrinking_factor() {
  shrinking_factor_ = 0.75f;
  clear_has_shrinking_factor();
}
inline float TrainerSpec::shrinking_factor() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.shrinking_factor)
  return shrinking_factor_;
}
inline void TrainerSpec::set_shrinking_factor(float value) {
  set_has_shrinking_factor();
  shrinking_factor_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.shrinking_factor)
}

// optional int32 num_threads = 16 [default = 16];
inline bool TrainerSpec::has_num_threads() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void TrainerSpec::set_has_num_threads() {
  _has_bits_[0] |= 0x00000200u;
}
inline void TrainerSpec::clear_has_num_threads() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void TrainerSpec::clear_num_threads() {
  num_threads_ = 16;
  clear_has_num_threads();
}
inline ::google::protobuf::int32 TrainerSpec::num_threads() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.num_threads)
  return num_threads_;
}
inline void TrainerSpec::set_num_threads(::google::protobuf::int32 value) {
  set_has_num_threads();
  num_threads_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.num_threads)
}

// optional int32 num_sub_iterations = 17 [default = 2];
inline bool TrainerSpec::has_num_sub_iterations() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void TrainerSpec::set_has_num_sub_iterations() {
  _has_bits_[0] |= 0x00000400u;
}
inline void TrainerSpec::clear_has_num_sub_iterations() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void TrainerSpec::clear_num_sub_iterations() {
  num_sub_iterations_ = 2;
  clear_has_num_sub_iterations();
}
inline ::google::protobuf::int32 TrainerSpec::num_sub_iterations() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.num_sub_iterations)
  return num_sub_iterations_;
}
inline void TrainerSpec::set_num_sub_iterations(::google::protobuf::int32 value) {
  set_has_num_sub_iterations();
  num_sub_iterations_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.num_sub_iterations)
}

// optional int32 max_sentencepiece_length = 20 [default = 16];
inline bool TrainerSpec::has_max_sentencepiece_length() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void TrainerSpec::set_has_max_sentencepiece_length() {
  _has_bits_[0] |= 0x00000800u;
}
inline void TrainerSpec::clear_has_max_sentencepiece_length() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void TrainerSpec::clear_max_sentencepiece_length() {
  max_sentencepiece_length_ = 16;
  clear_has_max_sentencepiece_length();
}
inline ::google::protobuf::int32 TrainerSpec::max_sentencepiece_length() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.max_sentencepiece_length)
  return max_sentencepiece_length_;
}
inline void TrainerSpec::set_max_sentencepiece_length(::google::protobuf::int32 value) {
  set_has_max_sentencepiece_length();
  max_sentencepiece_length_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.max_sentencepiece_length)
}

// optional bool split_by_unicode_script = 21 [default = true];
inline bool TrainerSpec::has_split_by_unicode_script() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void TrainerSpec::set_has_split_by_unicode_script() {
  _has_bits_[0] |= 0x00001000u;
}
inline void TrainerSpec::clear_has_split_by_unicode_script() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void TrainerSpec::clear_split_by_unicode_script() {
  split_by_unicode_script_ = true;
  clear_has_split_by_unicode_script();
}
inline bool TrainerSpec::split_by_unicode_script() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.split_by_unicode_script)
  return split_by_unicode_script_;
}
inline void TrainerSpec::set_split_by_unicode_script(bool value) {
  set_has_split_by_unicode_script();
  split_by_unicode_script_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.split_by_unicode_script)
}

// optional bool split_by_whitespace = 22 [default = true];
inline bool TrainerSpec::has_split_by_whitespace() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void TrainerSpec::set_has_split_by_whitespace() {
  _has_bits_[0] |= 0x00002000u;
}
inline void TrainerSpec::clear_has_split_by_whitespace() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void TrainerSpec::clear_split_by_whitespace() {
  split_by_whitespace_ = true;
  clear_has_split_by_whitespace();
}
inline bool TrainerSpec::split_by_whitespace() const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.split_by_whitespace)
  return split_by_whitespace_;
}
inline void TrainerSpec::set_split_by_whitespace(bool value) {
  set_has_split_by_whitespace();
  split_by_whitespace_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.split_by_whitespace)
}

// repeated string control_symbols = 30;
inline int TrainerSpec::control_symbols_size() const {
  return control_symbols_.size();
}
inline void TrainerSpec::clear_control_symbols() {
  control_symbols_.Clear();
}
inline const ::std::string& TrainerSpec::control_symbols(int index) const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.control_symbols)
  return control_symbols_.Get(index);
}
inline ::std::string* TrainerSpec::mutable_control_symbols(int index) {
  // @@protoc_insertion_point(field_mutable:sentencepiece.TrainerSpec.control_symbols)
  return control_symbols_.Mutable(index);
}
inline void TrainerSpec::set_control_symbols(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.control_symbols)
  control_symbols_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void TrainerSpec::set_control_symbols(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.control_symbols)
  control_symbols_.Mutable(index)->assign(std::move(value));
}
#endif
inline void TrainerSpec::set_control_symbols(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  control_symbols_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sentencepiece.TrainerSpec.control_symbols)
}
inline void TrainerSpec::set_control_symbols(int index, const char* value, size_t size) {
  control_symbols_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.TrainerSpec.control_symbols)
}
inline ::std::string* TrainerSpec::add_control_symbols() {
  // @@protoc_insertion_point(field_add_mutable:sentencepiece.TrainerSpec.control_symbols)
  return control_symbols_.Add();
}
inline void TrainerSpec::add_control_symbols(const ::std::string& value) {
  control_symbols_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.control_symbols)
}
#if LANG_CXX11
inline void TrainerSpec::add_control_symbols(::std::string&& value) {
  control_symbols_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.control_symbols)
}
#endif
inline void TrainerSpec::add_control_symbols(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  control_symbols_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sentencepiece.TrainerSpec.control_symbols)
}
inline void TrainerSpec::add_control_symbols(const char* value, size_t size) {
  control_symbols_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sentencepiece.TrainerSpec.control_symbols)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TrainerSpec::control_symbols() const {
  // @@protoc_insertion_point(field_list:sentencepiece.TrainerSpec.control_symbols)
  return control_symbols_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TrainerSpec::mutable_control_symbols() {
  // @@protoc_insertion_point(field_mutable_list:sentencepiece.TrainerSpec.control_symbols)
  return &control_symbols_;
}

// repeated string user_defined_symbols = 31;
inline int TrainerSpec::user_defined_symbols_size() const {
  return user_defined_symbols_.size();
}
inline void TrainerSpec::clear_user_defined_symbols() {
  user_defined_symbols_.Clear();
}
inline const ::std::string& TrainerSpec::user_defined_symbols(int index) const {
  // @@protoc_insertion_point(field_get:sentencepiece.TrainerSpec.user_defined_symbols)
  return user_defined_symbols_.Get(index);
}
inline ::std::string* TrainerSpec::mutable_user_defined_symbols(int index) {
  // @@protoc_insertion_point(field_mutable:sentencepiece.TrainerSpec.user_defined_symbols)
  return user_defined_symbols_.Mutable(index);
}
inline void TrainerSpec::set_user_defined_symbols(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.user_defined_symbols)
  user_defined_symbols_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void TrainerSpec::set_user_defined_symbols(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:sentencepiece.TrainerSpec.user_defined_symbols)
  user_defined_symbols_.Mutable(index)->assign(std::move(value));
}
#endif
inline void TrainerSpec::set_user_defined_symbols(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_defined_symbols_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:sentencepiece.TrainerSpec.user_defined_symbols)
}
inline void TrainerSpec::set_user_defined_symbols(int index, const char* value, size_t size) {
  user_defined_symbols_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.TrainerSpec.user_defined_symbols)
}
inline ::std::string* TrainerSpec::add_user_defined_symbols() {
  // @@protoc_insertion_point(field_add_mutable:sentencepiece.TrainerSpec.user_defined_symbols)
  return user_defined_symbols_.Add();
}
inline void TrainerSpec::add_user_defined_symbols(const ::std::string& value) {
  user_defined_symbols_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.user_defined_symbols)
}
#if LANG_CXX11
inline void TrainerSpec::add_user_defined_symbols(::std::string&& value) {
  user_defined_symbols_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:sentencepiece.TrainerSpec.user_defined_symbols)
}
#endif
inline void TrainerSpec::add_user_defined_symbols(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  user_defined_symbols_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:sentencepiece.TrainerSpec.user_defined_symbols)
}
inline void TrainerSpec::add_user_defined_symbols(const char* value, size_t size) {
  user_defined_symbols_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:sentencepiece.TrainerSpec.user_defined_symbols)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TrainerSpec::user_defined_symbols() const {
  // @@protoc_insertion_point(field_list:sentencepiece.TrainerSpec.user_defined_symbols)
  return user_defined_symbols_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TrainerSpec::mutable_user_defined_symbols() {
  // @@protoc_insertion_point(field_mutable_list:sentencepiece.TrainerSpec.user_defined_symbols)
  return &user_defined_symbols_;
}

// -------------------------------------------------------------------

// NormalizerSpec

// optional string name = 1;
inline bool NormalizerSpec::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NormalizerSpec::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NormalizerSpec::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NormalizerSpec::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& NormalizerSpec::name() const {
  // @@protoc_insertion_point(field_get:sentencepiece.NormalizerSpec.name)
  return name_.GetNoArena();
}
inline void NormalizerSpec::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sentencepiece.NormalizerSpec.name)
}
#if LANG_CXX11
inline void NormalizerSpec::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sentencepiece.NormalizerSpec.name)
}
#endif
inline void NormalizerSpec::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sentencepiece.NormalizerSpec.name)
}
inline void NormalizerSpec::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.NormalizerSpec.name)
}
inline ::std::string* NormalizerSpec::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:sentencepiece.NormalizerSpec.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NormalizerSpec::release_name() {
  // @@protoc_insertion_point(field_release:sentencepiece.NormalizerSpec.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NormalizerSpec::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.NormalizerSpec.name)
}

// optional bytes precompiled_charsmap = 2;
inline bool NormalizerSpec::has_precompiled_charsmap() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NormalizerSpec::set_has_precompiled_charsmap() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NormalizerSpec::clear_has_precompiled_charsmap() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NormalizerSpec::clear_precompiled_charsmap() {
  precompiled_charsmap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_precompiled_charsmap();
}
inline const ::std::string& NormalizerSpec::precompiled_charsmap() const {
  // @@protoc_insertion_point(field_get:sentencepiece.NormalizerSpec.precompiled_charsmap)
  return precompiled_charsmap_.GetNoArena();
}
inline void NormalizerSpec::set_precompiled_charsmap(const ::std::string& value) {
  set_has_precompiled_charsmap();
  precompiled_charsmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sentencepiece.NormalizerSpec.precompiled_charsmap)
}
#if LANG_CXX11
inline void NormalizerSpec::set_precompiled_charsmap(::std::string&& value) {
  set_has_precompiled_charsmap();
  precompiled_charsmap_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sentencepiece.NormalizerSpec.precompiled_charsmap)
}
#endif
inline void NormalizerSpec::set_precompiled_charsmap(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_precompiled_charsmap();
  precompiled_charsmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sentencepiece.NormalizerSpec.precompiled_charsmap)
}
inline void NormalizerSpec::set_precompiled_charsmap(const void* value, size_t size) {
  set_has_precompiled_charsmap();
  precompiled_charsmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.NormalizerSpec.precompiled_charsmap)
}
inline ::std::string* NormalizerSpec::mutable_precompiled_charsmap() {
  set_has_precompiled_charsmap();
  // @@protoc_insertion_point(field_mutable:sentencepiece.NormalizerSpec.precompiled_charsmap)
  return precompiled_charsmap_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NormalizerSpec::release_precompiled_charsmap() {
  // @@protoc_insertion_point(field_release:sentencepiece.NormalizerSpec.precompiled_charsmap)
  clear_has_precompiled_charsmap();
  return precompiled_charsmap_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NormalizerSpec::set_allocated_precompiled_charsmap(::std::string* precompiled_charsmap) {
  if (precompiled_charsmap != NULL) {
    set_has_precompiled_charsmap();
  } else {
    clear_has_precompiled_charsmap();
  }
  precompiled_charsmap_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), precompiled_charsmap);
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.NormalizerSpec.precompiled_charsmap)
}

// optional bool add_dummy_prefix = 3 [default = true];
inline bool NormalizerSpec::has_add_dummy_prefix() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NormalizerSpec::set_has_add_dummy_prefix() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NormalizerSpec::clear_has_add_dummy_prefix() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NormalizerSpec::clear_add_dummy_prefix() {
  add_dummy_prefix_ = true;
  clear_has_add_dummy_prefix();
}
inline bool NormalizerSpec::add_dummy_prefix() const {
  // @@protoc_insertion_point(field_get:sentencepiece.NormalizerSpec.add_dummy_prefix)
  return add_dummy_prefix_;
}
inline void NormalizerSpec::set_add_dummy_prefix(bool value) {
  set_has_add_dummy_prefix();
  add_dummy_prefix_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.NormalizerSpec.add_dummy_prefix)
}

// optional bool remove_extra_whitespaces = 4 [default = true];
inline bool NormalizerSpec::has_remove_extra_whitespaces() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NormalizerSpec::set_has_remove_extra_whitespaces() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NormalizerSpec::clear_has_remove_extra_whitespaces() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NormalizerSpec::clear_remove_extra_whitespaces() {
  remove_extra_whitespaces_ = true;
  clear_has_remove_extra_whitespaces();
}
inline bool NormalizerSpec::remove_extra_whitespaces() const {
  // @@protoc_insertion_point(field_get:sentencepiece.NormalizerSpec.remove_extra_whitespaces)
  return remove_extra_whitespaces_;
}
inline void NormalizerSpec::set_remove_extra_whitespaces(bool value) {
  set_has_remove_extra_whitespaces();
  remove_extra_whitespaces_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.NormalizerSpec.remove_extra_whitespaces)
}

// optional bool escape_whitespaces = 5 [default = true];
inline bool NormalizerSpec::has_escape_whitespaces() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NormalizerSpec::set_has_escape_whitespaces() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NormalizerSpec::clear_has_escape_whitespaces() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NormalizerSpec::clear_escape_whitespaces() {
  escape_whitespaces_ = true;
  clear_has_escape_whitespaces();
}
inline bool NormalizerSpec::escape_whitespaces() const {
  // @@protoc_insertion_point(field_get:sentencepiece.NormalizerSpec.escape_whitespaces)
  return escape_whitespaces_;
}
inline void NormalizerSpec::set_escape_whitespaces(bool value) {
  set_has_escape_whitespaces();
  escape_whitespaces_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.NormalizerSpec.escape_whitespaces)
}

// -------------------------------------------------------------------

// ModelProto_SentencePiece

// optional string piece = 1;
inline bool ModelProto_SentencePiece::has_piece() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModelProto_SentencePiece::set_has_piece() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModelProto_SentencePiece::clear_has_piece() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModelProto_SentencePiece::clear_piece() {
  piece_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_piece();
}
inline const ::std::string& ModelProto_SentencePiece::piece() const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.SentencePiece.piece)
  return piece_.GetNoArena();
}
inline void ModelProto_SentencePiece::set_piece(const ::std::string& value) {
  set_has_piece();
  piece_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sentencepiece.ModelProto.SentencePiece.piece)
}
#if LANG_CXX11
inline void ModelProto_SentencePiece::set_piece(::std::string&& value) {
  set_has_piece();
  piece_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sentencepiece.ModelProto.SentencePiece.piece)
}
#endif
inline void ModelProto_SentencePiece::set_piece(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_piece();
  piece_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sentencepiece.ModelProto.SentencePiece.piece)
}
inline void ModelProto_SentencePiece::set_piece(const char* value, size_t size) {
  set_has_piece();
  piece_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sentencepiece.ModelProto.SentencePiece.piece)
}
inline ::std::string* ModelProto_SentencePiece::mutable_piece() {
  set_has_piece();
  // @@protoc_insertion_point(field_mutable:sentencepiece.ModelProto.SentencePiece.piece)
  return piece_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelProto_SentencePiece::release_piece() {
  // @@protoc_insertion_point(field_release:sentencepiece.ModelProto.SentencePiece.piece)
  clear_has_piece();
  return piece_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelProto_SentencePiece::set_allocated_piece(::std::string* piece) {
  if (piece != NULL) {
    set_has_piece();
  } else {
    clear_has_piece();
  }
  piece_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), piece);
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.ModelProto.SentencePiece.piece)
}

// optional float score = 2;
inline bool ModelProto_SentencePiece::has_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModelProto_SentencePiece::set_has_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModelProto_SentencePiece::clear_has_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModelProto_SentencePiece::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline float ModelProto_SentencePiece::score() const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.SentencePiece.score)
  return score_;
}
inline void ModelProto_SentencePiece::set_score(float value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.ModelProto.SentencePiece.score)
}

// optional .sentencepiece.ModelProto.SentencePiece.Type type = 3 [default = NORMAL];
inline bool ModelProto_SentencePiece::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ModelProto_SentencePiece::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ModelProto_SentencePiece::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ModelProto_SentencePiece::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::sentencepiece::ModelProto_SentencePiece_Type ModelProto_SentencePiece::type() const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.SentencePiece.type)
  return static_cast< ::sentencepiece::ModelProto_SentencePiece_Type >(type_);
}
inline void ModelProto_SentencePiece::set_type(::sentencepiece::ModelProto_SentencePiece_Type value) {
  assert(::sentencepiece::ModelProto_SentencePiece_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:sentencepiece.ModelProto.SentencePiece.type)
}

// -------------------------------------------------------------------

// ModelProto

// repeated .sentencepiece.ModelProto.SentencePiece pieces = 1;
inline int ModelProto::pieces_size() const {
  return pieces_.size();
}
inline void ModelProto::clear_pieces() {
  pieces_.Clear();
}
inline const ::sentencepiece::ModelProto_SentencePiece& ModelProto::pieces(int index) const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.pieces)
  return pieces_.Get(index);
}
inline ::sentencepiece::ModelProto_SentencePiece* ModelProto::mutable_pieces(int index) {
  // @@protoc_insertion_point(field_mutable:sentencepiece.ModelProto.pieces)
  return pieces_.Mutable(index);
}
inline ::sentencepiece::ModelProto_SentencePiece* ModelProto::add_pieces() {
  // @@protoc_insertion_point(field_add:sentencepiece.ModelProto.pieces)
  return pieces_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::sentencepiece::ModelProto_SentencePiece >*
ModelProto::mutable_pieces() {
  // @@protoc_insertion_point(field_mutable_list:sentencepiece.ModelProto.pieces)
  return &pieces_;
}
inline const ::google::protobuf::RepeatedPtrField< ::sentencepiece::ModelProto_SentencePiece >&
ModelProto::pieces() const {
  // @@protoc_insertion_point(field_list:sentencepiece.ModelProto.pieces)
  return pieces_;
}

// optional .sentencepiece.TrainerSpec trainer_spec = 2;
inline bool ModelProto::has_trainer_spec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModelProto::set_has_trainer_spec() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModelProto::clear_has_trainer_spec() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModelProto::clear_trainer_spec() {
  if (trainer_spec_ != NULL) trainer_spec_->::sentencepiece::TrainerSpec::Clear();
  clear_has_trainer_spec();
}
inline const ::sentencepiece::TrainerSpec& ModelProto::trainer_spec() const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.trainer_spec)
  return trainer_spec_ != NULL ? *trainer_spec_
                         : *::sentencepiece::TrainerSpec::internal_default_instance();
}
inline ::sentencepiece::TrainerSpec* ModelProto::mutable_trainer_spec() {
  set_has_trainer_spec();
  if (trainer_spec_ == NULL) {
    trainer_spec_ = new ::sentencepiece::TrainerSpec;
  }
  // @@protoc_insertion_point(field_mutable:sentencepiece.ModelProto.trainer_spec)
  return trainer_spec_;
}
inline ::sentencepiece::TrainerSpec* ModelProto::release_trainer_spec() {
  // @@protoc_insertion_point(field_release:sentencepiece.ModelProto.trainer_spec)
  clear_has_trainer_spec();
  ::sentencepiece::TrainerSpec* temp = trainer_spec_;
  trainer_spec_ = NULL;
  return temp;
}
inline void ModelProto::set_allocated_trainer_spec(::sentencepiece::TrainerSpec* trainer_spec) {
  delete trainer_spec_;
  trainer_spec_ = trainer_spec;
  if (trainer_spec) {
    set_has_trainer_spec();
  } else {
    clear_has_trainer_spec();
  }
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.ModelProto.trainer_spec)
}

// optional .sentencepiece.NormalizerSpec normalizer_spec = 3;
inline bool ModelProto::has_normalizer_spec() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModelProto::set_has_normalizer_spec() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModelProto::clear_has_normalizer_spec() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModelProto::clear_normalizer_spec() {
  if (normalizer_spec_ != NULL) normalizer_spec_->::sentencepiece::NormalizerSpec::Clear();
  clear_has_normalizer_spec();
}
inline const ::sentencepiece::NormalizerSpec& ModelProto::normalizer_spec() const {
  // @@protoc_insertion_point(field_get:sentencepiece.ModelProto.normalizer_spec)
  return normalizer_spec_ != NULL ? *normalizer_spec_
                         : *::sentencepiece::NormalizerSpec::internal_default_instance();
}
inline ::sentencepiece::NormalizerSpec* ModelProto::mutable_normalizer_spec() {
  set_has_normalizer_spec();
  if (normalizer_spec_ == NULL) {
    normalizer_spec_ = new ::sentencepiece::NormalizerSpec;
  }
  // @@protoc_insertion_point(field_mutable:sentencepiece.ModelProto.normalizer_spec)
  return normalizer_spec_;
}
inline ::sentencepiece::NormalizerSpec* ModelProto::release_normalizer_spec() {
  // @@protoc_insertion_point(field_release:sentencepiece.ModelProto.normalizer_spec)
  clear_has_normalizer_spec();
  ::sentencepiece::NormalizerSpec* temp = normalizer_spec_;
  normalizer_spec_ = NULL;
  return temp;
}
inline void ModelProto::set_allocated_normalizer_spec(::sentencepiece::NormalizerSpec* normalizer_spec) {
  delete normalizer_spec_;
  normalizer_spec_ = normalizer_spec;
  if (normalizer_spec) {
    set_has_normalizer_spec();
  } else {
    clear_has_normalizer_spec();
  }
  // @@protoc_insertion_point(field_set_allocated:sentencepiece.ModelProto.normalizer_spec)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace sentencepiece

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::sentencepiece::TrainerSpec_ModelType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sentencepiece::TrainerSpec_ModelType>() {
  return ::sentencepiece::TrainerSpec_ModelType_descriptor();
}
template <> struct is_proto_enum< ::sentencepiece::ModelProto_SentencePiece_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sentencepiece::ModelProto_SentencePiece_Type>() {
  return ::sentencepiece::ModelProto_SentencePiece_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_2fsentencepiece_5fmodel_2eproto__INCLUDED
